In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from scipy.optimize import curve_fit

mobile_PATH = '/home/is/shuntaro-o/dev/compare_population_and_tweet_number/data/mobile/Tokyostation/Tokyostation_2021.npy'
twitter_PATH = '/home/is/shuntaro-o/dev/compare_population_and_tweet_number/data/twitter/Tokyostation_2021/Tokyostation_3zi_2021.npy'
outlier_twitter__PATH = '/home/is/shuntaro-o/dev/compare_population_and_tweet_number/data/twitter/Tokyostation_2021/outlier/Tokyostation_3zi_2021.npy'

mobile = np.load(mobile_PATH)
twitter = np.load(twitter_PATH)
mobile_flatten = mobile.flatten()
twitter_flatten = twitter.flatten()

In [26]:
#make labels
day_list_long = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
day_list_short = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30']
day_list_Feb = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28']
hour_list = ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
x_label = []
for month in ['01','02','03','04','05','06','07','08','09','10','11','12']:
    if month in ['01', '03', '05', '07', '08','10', '12']:
        day_list = day_list_long
    elif month == '02':
        day_list = day_list_Feb
    else:
        day_list = day_list_short
    for day in day_list:
        for hour in range(0,24):
            hour = str(hour)
            key = int('21'+ month + day + hour)
            key = str(key)
            x_label.append(key)

## 一時間ごと

In [27]:
mobile_flatten_stand =preprocessing.scale(mobile_flatten)
twitter_flatten_stand = preprocessing.scale(twitter_flatten)

In [28]:
# ズレてる...
list_mobile_holiday = []
list_mobile_workday = []

list_twitter_holiday = []
list_twitter_workday = []

for i in range(0,365):
    if i%7 == 0:
        list_mobile_holiday.append(mobile[i].tolist())
        list_twitter_holiday.append(twitter[i].tolist())
    if i%7 == 1:
        list_mobile_holiday.append(mobile[i].tolist())
        list_twitter_holiday.append(twitter[i].tolist())
    if i%7 == 2:
        list_mobile_workday.append(mobile[i].tolist())
        list_twitter_workday.append(twitter[i].tolist())
    if i%7 == 3:
        list_mobile_workday.append(mobile[i].tolist())
        list_twitter_workday.append(twitter[i].tolist())
    if i%7 == 4:
        list_mobile_workday.append(mobile[i].tolist())
        list_twitter_workday.append(twitter[i].tolist())
    if i%7 == 5:
        list_mobile_workday.append(mobile[i].tolist())
        list_twitter_workday.append(twitter[i].tolist())
    if i%7 == 6:
        list_mobile_workday.append(mobile[i].tolist())
        list_twitter_workday.append(twitter[i].tolist())



In [29]:
list_mobile_holiday = np.array(list_mobile_holiday)
list_mobile_workday = np.array(list_mobile_workday)
list_twitter_holiday  = np.array(list_twitter_holiday)
list_twitter_workday  = np.array(list_twitter_workday)

In [30]:
list_mobile_holiday_flatten = list_mobile_holiday.flatten()
list_mobile_workday_flatten = list_mobile_workday.flatten()
list_twitter_holiday_flatten  = list_twitter_holiday.flatten()
list_twitter_workday_flatten = list_twitter_workday.flatten()

In [31]:
# x: input(人口)
def exp(x, k=1):
    rvalue = 0.0
    rvalue =  np.exp(k*x)
    return rvalue
def line(x,a=2):
    return a*x
def power(x, k=2):
    return (x**k)

## exp

In [32]:
x = list_mobile_workday_flatten
y= list_twitter_workday_flatten
#x = x/(sum(x)/sum(y))
popt_exp_workday, pcov_exp_workday = curve_fit(exp, x, y, p0=[0.001])
popt_line_workday, pcov_line_workday = curve_fit(line, x, y)
fitting_exp_workday = exp(x, *popt_exp_workday)
popt_exp_workday

array([2.30598133e-05])

In [33]:
x = list_mobile_holiday_flatten
y= list_twitter_holiday_flatten
#x = x/(sum(x)/sum(y))
popt_exp_holiday, pcov_exp_holiday = curve_fit(exp, x, y, p0=[0.001])
popt_line_holiday, pcov_line_holiday = curve_fit(line, x, y)
fitting_exp_holiday = exp(x, *popt_exp_holiday)
popt_exp_holiday

array([2.53729711e-05])

In [34]:
fitting_exp_workday = fitting_exp_workday.reshape(260,24)
fitting_exp_holiday = fitting_exp_holiday.reshape(105,24)

In [35]:
fitting_exp = np.concatenate([fitting_exp_workday, fitting_exp_holiday])
fitting_exp_flatten = fitting_exp.flatten()

## power

In [36]:
x = list_mobile_workday_flatten
y= list_twitter_workday_flatten
#x = x/(sum(x)/sum(y))
popt_power_workday, pcov_power_workday = curve_fit(power, x, y, p0=[0.001])
fitting_power_workday = power(x, *popt_power_workday)
popt_power_workday

array([0.22012258])

In [37]:
x = list_mobile_holiday_flatten
y= list_twitter_holiday_flatten
#x = x/(sum(x)/sum(y))
popt_power_holiday, pcov_power_holiday = curve_fit(power, x, y, p0=[0.001])
fitting_power_holiday = power(x, *popt_power_holiday)
popt_power_holiday

array([0.24556755])

In [38]:
fitting_power_workday = fitting_power_workday.reshape(260,24)
fitting_power_holiday = fitting_power_holiday.reshape(105,24)

In [39]:
fitting_power = np.concatenate([fitting_power_workday, fitting_power_holiday])
fitting_power_flatten = fitting_power.flatten()

## line

In [40]:
x = list_mobile_workday_flatten
y= list_twitter_workday_flatten
#x = x/(sum(x)/sum(y))
popt_line_workday, pcov_line_workday = curve_fit(line, x, y, p0=[0.001])
fitting_line_workday = line(x, *popt_line_workday)
popt_line_workday

array([0.00014104])

In [41]:
x = list_mobile_holiday_flatten
y= list_twitter_holiday_flatten
#x = x/(sum(x)/sum(y))
popt_line_holiday, pcov_line_holiday = curve_fit(line, x, y, p0=[0.001])
fitting_line_holiday = line(x, *popt_line_holiday)
popt_line_holiday

array([0.00020749])

In [42]:
popt_line_workday/popt_line_holiday

array([0.67976039])

In [43]:
fitting_line_workday = fitting_line_workday.reshape(260,24)
fitting_line_holiday = fitting_line_holiday.reshape(105,24)

In [44]:
fitting_line = np.concatenate([fitting_line_workday, fitting_line_holiday])
fitting_line_flatten = fitting_line.flatten()

In [45]:
import plotly.graph_objects as go
fig = go.Figure(data=[
    #go.Scatter(x=x_label, y=mobile_flatten_stand, name='mobile'),
    go.Scatter(x=x_label, y=twitter_flatten, name="twitter"),
    go.Scatter(x=x_label, y=fitting_exp_flatten, name="exp"),
    go.Scatter(x=x_label, y=fitting_line_flatten, name="line"),
    go.Scatter(x=x_label, y=fitting_power_flatten, name="power"),
])
fig.update_layout(xaxis=dict(title='Time'),
                 yaxis=dict(title='Tweet Number'),
                 title='Tokyo Station 2021(divide_holiday_and_workday)')
fig.show()

In [46]:
o =twitter_flatten #実測データ例
e = fitting_exp_flatten #モデル計算された数値例
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'exp決定係数: {r_squared}')
#カイ２乗誤差
print(f'expカイ２乗誤差: {np.sum(((o-e)**2)/e)}')
print(f'exp平均２乗誤差: {np.sum(((o-e)**2)/(len(e)))}')

exp決定係数: -0.3178161852549539
expカイ２乗誤差: 388705.9464692675
exp平均２乗誤差: 102.80425180449224


In [47]:
o =twitter_flatten #実測データ例
e = fitting_line_flatten #モデル計算された数値例
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'line決定係数: {r_squared}')
#カイ２乗誤差
print(f'lineカイ２乗誤差: {np.sum(((o-e)**2)/e)}')
print(f'line平均２乗誤差: {np.sum(((o-e)**2)/(len(e)))}')

line決定係数: 0.02528421681936366
lineカイ２乗誤差: 222393.9982302855
line平均２乗誤差: 76.03862202719012


In [48]:
o =twitter_flatten #実測データ例
e = fitting_power_flatten #モデル計算された数値例
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'power決定係数: {r_squared}')
#カイ２乗誤差
print(f'powerカイ２乗誤差: {np.sum(((o-e)**2)/e)}')
print(f'power平均２乗誤差: {np.sum(((o-e)**2)/(len(e)))}')

power決定係数: 0.2588913047309209
powerカイ２乗誤差: 50719.69456258447
power平均２乗誤差: 57.81468293941239
