In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from scipy.optimize import curve_fit
from scipy import stats
mobile = np.load('/home/is/shuntaro-o/dev/compare_population_and_tweet_number/data/mobile/Tokyostation/Tokyostation_2021.npy')
twitter = np.load('/home/is/shuntaro-o/dev/compare_population_and_tweet_number/data/twitter/Tokyostation_2021/Tokyostation_3zi_2021.npy')


In [127]:
month7_mobile = mobile[180:211,:]
month7_twitter = twitter[180:211,:]
list_month7_holiday = [2,3,9,10,16,17,18,23,24,30,31]
list_month7_holiday = [n - 1 for n in list_month7_holiday]
day_list_long = [n for n in range(0,31)]
list_month7_workday = list(set(day_list_long) - set(list_month7_holiday))

In [128]:
month7_mobile_workday = month7_mobile[list_month7_workday]
month7_mobile_holiday = month7_mobile[list_month7_holiday]
month7_twitter_workday = month7_twitter[list_month7_workday]
month7_twitter_holiday = month7_twitter[list_month7_holiday]
month7_mobile_workday_flatten = month7_mobile_workday.flatten()
month7_mobile_holiday_flatten = month7_mobile_holiday.flatten()
month7_twitter_workday_flatten = month7_twitter_workday.flatten()
month7_twitter_holiday_flatten = month7_twitter_holiday.flatten()
month7_mobile_workday_flatten_stand =preprocessing.scale(month7_mobile_workday_flatten)
month7_mobile_holiday_flatten_stand = preprocessing.scale(month7_mobile_holiday_flatten)
month7_twitter_workday_flatten_stand = preprocessing.scale(month7_twitter_workday_flatten)
month7_twitter_holiday_flatten_stand = preprocessing.scale(month7_twitter_holiday_flatten)

In [129]:
day_list_long = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
hour_list = ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
x_label_workday = []
list_month7_workday_for_label = [n + 1 for n in list_month7_workday]
for month in ['07']:
    for day in list_month7_workday_for_label:
        for hour in hour_list:
            hour = str(hour)
            day = str(day)
            key = int('21'+ month + day + hour)
            key = str(key)
            x_label_workday.append(key)

In [130]:
import plotly.graph_objects as go
fig = go.Figure(data=[
    go.Scatter(x=x_label_workday, y=month7_mobile_workday_flatten_stand, name='mobile'),
    go.Scatter(x=x_label_workday, y=month7_twitter_workday_flatten_stand , name="twitter"),
])
fig.show()

In [131]:
day_list_long = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
hour_list = ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
x_label_holiday = []
list_month7_holiday_for_label = [n + 1 for n in list_month7_holiday]
for month in ['07']:
    for day in list_month7_holiday_for_label:
        for hour in hour_list:
            hour = str(hour)
            day = str(day)
            key = int('21'+ month + day + hour)
            key = str(key)
            x_label_holiday.append(key)

In [132]:
import plotly.graph_objects as go
fig = go.Figure(data=[
    go.Scatter(x=x_label_holiday, y=month7_mobile_holiday_flatten_stand, name='mobile'),
    go.Scatter(x=x_label_holiday, y=month7_twitter_holiday_flatten_stand , name="twitter"),
])
fig.show()

In [177]:
def exp(ps, a):
    rvalue = 0.0
    rvalue =  np.exp(a * ps)
    return rvalue

def line(x, a, b):
    return a*x + b

def power(ps, a):
    return ps**a

In [178]:
x = month7_mobile_workday_flatten
y= month7_twitter_workday_flatten
#x = x/(sum(x)/sum(y))
popt_exp_workday, pcov_exp_workday = curve_fit(exp, x, y, p0=[0.001])
popt_line_workday, pcov_line_workday = curve_fit(line, x, y)
fitting_exp_workday = exp(x, *popt_exp_workday)
fitting_line_workday = line(x, *popt_line_workday)
popt_exp_workday

array([2.3315994e-05])

In [179]:
x = month7_mobile_holiday_flatten
y= month7_twitter_holiday_flatten
#x = x/(sum(x)/sum(y))
popt_exp_holiday, pcov_exp_holiday = curve_fit(exp, x, y, p0=[0.001])
popt_line_holiday, pcov_line_holiday = curve_fit(line, x, y)
fitting_exp_holiday = exp(x, *popt_exp_holiday)
fitting_line_holiday = line(x, *popt_line_holiday)
popt_exp_holiday

array([2.43701914e-05])

In [188]:
x = month7_mobile_workday_flatten
y= month7_twitter_workday_flatten
#x = x/(sum(x)/sum(y))
popt_power_workday, pcov_power_workday = curve_fit(power, x, y, p0=[0.001])
fitting_power_workday = power(x, *popt_power_workday)
popt_power_workday

array([0.22271296])

In [189]:
x = month7_mobile_holiday_flatten
y= month7_twitter_holiday_flatten
#x = x/(sum(x)/sum(y))
popt_power_holiday, pcov_power_holiday = curve_fit(power, x, y, p0=[0.001])
fitting_power_holiday = power(x, *popt_power_holiday)
popt_power_holiday

array([0.22597655])

## 平日評価

In [191]:
import plotly.graph_objects as go
fig = go.Figure(data=[
    #go.Scatter(x=x_label_workday, y=mobile_flatten
    go.Scatter(x=x_label_workday, y=month7_twitter_workday_flatten, name="twitter"),
    go.Scatter(x=x_label_workday, y=fitting_exp_workday, name="exp"), 
    go.Scatter(x=x_label_workday, y=fitting_line_workday, name="line"),
    go.Scatter(x=x_label_workday, y=fitting_power_workday, name="power"),
])
fig.show()

In [181]:
o = month7_twitter_workday_flatten
e = fitting_exp_workday
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: -0.6383025289062245
カイ２乗誤差: 20627.708726851786


In [182]:
o = month7_twitter_workday_flatten
e = fitting_line_workday
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: 0.07975290803988921
カイ２乗誤差: 2816.8998827069245


## 休日評価

In [183]:
import plotly.graph_objects as go
fig = go.Figure(data=[
    #go.Scatter(x=x_label_holiday, y=mobile_flatten_stand, name='mobile'),
    go.Scatter(x=x_label_holiday, y=month7_twitter_holiday_flatten, name="twitter"),
    go.Scatter(x=x_label_holiday, y=fitting_exp_holiday, name="exp"),
    go.Scatter(x=x_label_holiday, y=fitting_line_holiday, name="line"),
])
fig.show()

In [184]:
o = month7_twitter_holiday_flatten
e = fitting_exp_holiday
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: -0.5067575201822734
カイ２乗誤差: 9976.220578779958


In [185]:
o = month7_twitter_holiday_flatten
e = fitting_line_holiday
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: 0.13613762263440987
カイ２乗誤差: 1481.7478814368174


## まとめた評価

In [186]:
o = np.concatenate([month7_twitter_workday_flatten, month7_twitter_holiday_flatten])
e = np.concatenate([fitting_exp_workday, fitting_exp_holiday])
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: -0.5894359759083765
カイ２乗誤差: 30603.92930563174


In [187]:
o = np.concatenate([month7_twitter_workday_flatten, month7_twitter_holiday_flatten])
e = np.concatenate([fitting_line_workday, fitting_line_holiday])
residuals =  o - e #残渣
rss = np.sum(residuals**2)      #残差平方和: residual sum of squares = rss
tss = np.sum((o-np.mean(o))**2) #全平方和: total sum of squares = tss
r_squared = 1 - (rss / tss)     #決定係数R^2
 
print(f'決定係数: {r_squared}')
#カイ２乗誤差
print(f'カイ２乗誤差: {np.sum(((o-e)**2)/e)}')

決定係数: 0.10082896788527573
カイ２乗誤差: 4298.647764143742
